
[system]
	#Determines whether to grant starting items at the beginning of the game.
	"starting item" = true
	#Determines whether the armor has a passive effect.
	"armor passive" = true
	#Determines whether the weapon has a passive effect.
	"weapon ability" = true
	#Determines whether the boss will destroy blocks. (If the boss gets stuck in a wall, it will always activate)
	"bosses break block" = false
	#Determines whether the boss will gain buff effects.
	"slu boss buff" = false
	#The higher this value is, the higher the natural generation probability of sealstone(monster) becomes. (Max: 100)
	"monster sealstone chance" = 80.0
	#The higher this value is, the higher the natural generation probability of sealstone(npc) becomes. (Max: 100)
	"npc sealstone chance" = 80.0
	#The higher this value is, the higher the natural generation probability of sealstone(boss) becomes. (Max: 100)
	"boss sealstone chance" = 80.0

